// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujwaK-b_nL-JFpAsSHxjyTKSS3keRb64',
    appId: '1:1096109822019:android:d171e2a6d38551f73644f6',
    messagingSenderId: '1096109822019',
    projectId: 'roomunity-3f23e',
    storageBucket: 'roomunity-3f23e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQPPqqbd9vagfFYBdGl_v43gDI4NBhJw',
    appId: '1:1096109822019:ios:5a6817f9b689a3843644f6',
    messagingSenderId: '1096109822019',
    projectId: 'roomunity-3f23e',
    storageBucket: 'roomunity-3f23e.firebasestorage.app',
    androidClientId: '1096109822019-1kdu7onfv5sq0o9u0oiogrlcce6kmlja.apps.googleusercontent.com',
    iosClientId: '1096109822019-m58f7d579nmcbka8m9mnltu45riq890p.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomunity',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKwLr90FTTABd-tKqiPKV5jHlst8S3es',
    appId: '1:1096109822019:web:74d6c4f80d8e0e0c3644f6',
    messagingSenderId: '1096109822019',
    projectId: 'roomunity-3f23e',
    authDomain: 'roomunity-3f23e.firebaseapp.com',
    storageBucket: 'roomunity-3f23e.firebasestorage.app',
    measurementId: 'G-V4K8C7JMXZ',
  );

}